version: '2.3'

volumes:
  grafana-data:
  influxdb-data:

services:
  meli-proxy:
    container_name: meli-proxy
    build:
      context: .
      dockerfile: proxy-meli.dockerfile
    volumes:
      - ./extras/application-routes.yml:/home/gradle/build/libs/application-routes.yml
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_METRICS_EXPORT_STATSD_HOST=telegraf
  redis:
    container_name: redis
    image: redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "6379:6379"
  telegraf:
    container_name: telegraf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    image: telegraf:1.5.3-alpine
    volumes:
      - ./extras/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    container_name: influxdb
    image: influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    container_name: grafana
    image: grafana/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"