spring:
  application:
    name: meliProxy
  profiles:
    include: 'routes'
  redis:
    embeded:
      enabled: false
    host: localhost
    password: 
    port: 6379
  metrics:
    export:
      statsd:
        host: localhost
        port: 8125    
management:
  port: ${server.port}
  context-path: /management
  security:
    enabled: false

zuul:
  #sslHostnameValidationEnabled: false
  #addHostHeader: true
  #addProxyHeaders: false
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  #ignoreSecurityHeaders: false
  routes:
    meliItems:
      path: /items/**
      stripPrefix: false
      serviceId: meliproxyId
    meliCategories:
      path: /categories/**
      stripPrefix: false
      serviceId: meliproxyId
    meli:
      path: /**
      stripPrefix: false
      serviceId: meliproxyId
  ratelimit:
    enabled: true
    policies:
      meliItems:
        limit: 10
        refresh-interval: 60
        type:
          - origin
      meliCategories:
        limit: 10
        refresh-interval: 60
        type:
          - origin
          - user_agent
      meli:
        limit: 10
        refresh-interval: 60
        type:
          - origin
          - user_agent
meliproxyId:
  ribbon:
    listOfServers: https://api.mercadolibre.com:443
    IsSecure: true
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList     

server:
  port: 8080
  #context-path: /

##LOW LEVEL CONFIG
#We will use thread strategy because is safer.
zuul.ribbonIsolationStrategy: SEMAPHORE # the other value is THREAD
#zuul.threadPool.useSeparateThreadPools: true
#zuul.threadPool.threadPoolKeyPrefix: apigateway

javax.net.ssl.trustStore: classpath:cacerts 

ribbon:
  IsSecure: true
  TrustStore: classpath:cacerts
  TrustStorePassword : changeit

#ribbon.ConnectTimeout: 5000
#ribbon.ReadTimeout: 5000
#ribbon.MaxAutoRetries: 1
#ribbon.MaxAutoRetriesNextServer: 1
#ribbon.okToRetryOnAllErrors:  true
#ribbon.OkToRetryOnAllOperations: true
ribbon.trustSelfSigned: true
#zuul.host.maxTotalConnections: 200
#zuul.host.maxPerRouteConnections: 100

zuul.retryable: true

logging:
  level:
    ROOT: WARN
    org.springframework: WARN
    com.meli.proxy: INFO
    com.intraway.technology: WARN
    com.netflix.zuul: WARN
    #PUT IT IN DEBUG TO SEE HOW THE CONNECTION IS ESTABLISHED
    org.apache.http: WARN
