{
 "title": "Proxy-MELI",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "measurement": "uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.melicategoriesproxyid.requestcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "categories" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.meliitemsproxyid.requestcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "items" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.meligeneralproxyid.requestcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "general" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixthreadpool.proxymelimelicategoriesproxyid.currenttaskcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "categories" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixthreadpool.proxymelimeliitemsproxyid.currenttaskcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "items" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixthreadpool.proxymelimeligeneralproxyid.currenttaskcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "general" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Classes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "classes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.melicategoriesproxyid.99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "categories 99th" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.meligeneralproxyid.99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "general 99th" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "gauge.servo.hystrix.hystrixcommand.ribboncommand.meliitemsproxyid.99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "items 99th" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "Cpu Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  },
  {
   "title": "RateLimit Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "counter.servo.meli.ratelimit.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "general" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "counter.servo.melicategories.ratelimit.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "categories" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "counter.servo.meliitems.ratelimit.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "items" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "PROXI_MELI" }
     ]
    }
   ]
  }
 ]
}